[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "./start.sh"
